### ISSUE TITLE
Externalize embedded theme data

### ISSUE THREAD

**Issue by ElArtista** [lemnos/theme.sh#29]
It is always better to separate functionality from data.
It would be nice if we moved the theme data in some folder outside the script, preferably `~/.local/share/themes/`

**Comment by rvaiya** [comment]
theme.sh is intentionally designed to be self contained so the user doesn't have to manually manage a theme directory on multiple machines. The idea is that you can just `scp theme.sh <host>:.`  and have all the themes available. Adding themes to the script is trivial via `-a`.  Is there a particular use case you have in mind?

**Comment by ElArtista** [comment]
Yes, firstly tracking with version control is much more flexible when using different files.
Secondly, this would allow integration with different tools that either fetch or generate colorschemes (like pywal).
Either way there is a case for both embedded and non embedded colorschemes, maybe support for both is a viable answer too.

**Comment by lemnos** [comment]
> Yes, firstly tracking with version control is much more flexible when using different files.

This depends on the files in question. The internal storage format of the script is designed to be human readable and easily diffable. The same cannot necessarily be said for many file formats, so diffability varies independently from the number of files involved. In this case it would arguably make the diff more noisy and would materially affect portability.  Having said that, I discourage maintaining private forks anyway with the goal of having as many themes upstreamed as possible.

> Secondly, this would allow integration with different tools that either fetch or generate colorschemes (like pywal).

The script is already composable. You can feed themes to STDIN to apply them. If you *really* want to manage your own themes you can just generate them and then do `theme.sh < ~/.themes/mytheme`.

> Either way there is a case for both embedded and non embedded colorschemes, maybe support for both is a viable answer too.

I considered this at the outset but decided against it, though I am open to reconsidering it if a good case can be made.

**Comment by ElArtista** [comment]
I totally respect your decision, my final points are these:
- Sometimes you want to track just the tool/script but not the data.
- Having a pack mechanism is most commonly a convenience feature not the primary/only method of associating data with a tool
- Separating things adheres better to the linux philosophy.
If you believe that none of these have a fit in the project's goal/purpose, please feel free to close the issue!

**Comment by lemnos** [comment]
I totally respect your decision, my final points are these:

> Sometimes you want to track just the tool/script but not the data.

If by 'track' you mean with version control, then it is worth noting that each theme has its own file in this repository. They get bundled into the final product in bin/ when make is run. If you want to maintain a private repo you can follow the same approach.

> Having a pack mechanism is most commonly a convenience feature not the primary/only method of associating data with a tool

You can still use the script without any themes. `src/theme.sh` doesn't contain any scripts and is runnable on its own if you want to roll your own (with `-a`) or just use it to apply themes from stdin.

> Separating things adheres better to the linux philosophy.

I would normally be inclined to agree, my rationale for making an exception in this case are:

 - There are a finite and large number of themes in the wild. Rather than requiring users to have to `catch em all™` it makes sense to feed back into a master repo.
 - Theme definitions are small and useful enough to bundle into the script.
 - Having themes in multiple locations can be confusing (e.g `is x theme in ~/.themes or builtin?`) - Encouraging users to maintain their own `~/.themes/` directory discourages them from upstreaming new themes.
 - Having all of the themes bundled into a single file allows users to write scripts which hardcode theme names and rely on these being available on any system which has `theme.sh`.
 - It is still possible to use theme.sh as part of a custom theme generation pipeline

**Comment by ElArtista** [comment]
Good points.

Seeing that stdin can be used as an alternative source for themes (from the embedded ones), the only feature that is missing to use it without the embedded themes is a mechanism to list multiple themes piped in stdin in order for either `cat ~/.local/share/themes/* | theme.sh -l` or something like `theme.sh -l <(ls ~/.local/share/themes/*)` to work.

Anyway, I understand that this is not the primary focus of the project, so If you believe that the general public will not want this, feel free to close it!

**Comment by lemnos** [comment]
`cat ~/.local/share/themes/* | theme.sh -l`

This wouldn't work, assuming each file contains a theme definition. The file names are not preserved in the input stream. It would be possible to consume theme files as arguments (e.g `theme.sh -l <file>...`) or have the script consume something similar to the internal format, in which each theme is preceded by its name and terminated with a newline, but at that point you might as well just manage the names in your wrapper script (or use `-a`).

> Anyway, I understand that this is not the primary focus of the project, so If you believe that the general public will not want or make use of this, feel free to close it!

I am closing this, but I am open to reconsidering support for external themes if there is greater demand and a good real world use case. Feel free to open another issue or revive this one if you wish to pursue it.
